# Generated by Django 3.0.2 on 2021-05-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user_number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
