# Generated by Django 3.0.2 on 2021-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemsite', '0002_favorites_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Category/%Y/%m/%d'),
        ),
    ]
